# Version Catalog (toml file)
#   Learn about this file at: https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
#   If you make changes to this file, you'll first need either:
#     * click the "Reload All Gradle Projects" button in IntelliJ
#     * or run ./gradlew
#   to regenerate the java files (under the <root>/.gradle folder) which is then used by the build.gradle.kts file(s).

[versions]
hamcrest = "3.0"
junit-jupiter = "5.11.4"


[libraries]
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }