package sfca.rulesets.appexchange_xml;

public class ProtectSensitiveDataTest {
        /*
         NOTE: A TEST BASED ON SimpleAggregatorTst CAN'T WORK DUE TO THE WAY THE RULE IS WRITTEN SINCE IT DEPENDS ON THE
         NAMES OF THE FILES IN A SALESFORCE PROJECT. THIS RULE REALLY ISN'T ONE THAT SHOULD BE WRITTEN AS A PMD RULE IN
         MY OPINION SINCE WHILE PROCESSING A *.field-meta.xml FILE IT ATTEMPTS TO ALSO LOOK AT AND PROCESS
         *.object-meta.xml FILES AS WELL, WHICH THIS TYPE OF TESTING FRAMEWORK CAN'T HANDLE.
         SO THE SECURITY TEAM WILL HAVE TO WRITE A CUSTOM TEST FOR THIS IF WE WANT COVERAGE FOR THIS RULE.
         */
}
